In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
master= pd.read_csv("../data/processed/master.csv")

In [5]:
drop_cols = [
    "Name_rat",
    "NSE Code_rat",
    "Industry_rat",
    "Days Receivable Outstanding",
    "signal"
]

for col in drop_cols:
    if col in master.columns:
        master.drop(columns=col, inplace=True)

for col in ["t_1_price"]:
    if col in master.columns:
        master.drop(columns=col, inplace=True)

In [16]:
drop_obj = [
    "Name_bal",
    "NSE Code_bal",
    "BSE Code_bal",
    "join_key"
]

drop_obj = [c for c in drop_obj if c in X.columns]

X = X.drop(columns=drop_obj)

In [18]:
if "Credit rating" in X.columns:
    X = X.drop(columns=["Credit rating"])

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [19]:
X.select_dtypes(include="object").columns

/tmp/ipykernel_8585/2213039483.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns

Index(['Industry_bal'], dtype='str')

In [20]:
master["future_return"].isnull().sum()

np.int64(1)

In [21]:
master = master[
    master["future_return"].notna()
]

In [22]:
master["future_return"].isnull().sum()

np.int64(0)

In [26]:
X.columns.tolist()

['Name_bal',
 'BSE Code_bal',
 'NSE Code_bal',
 'Industry_bal',
 'Current Price_bal',
 'Debt',
 'Equity capital',
 'Preference capital',
 'Reserves',
 'Secured loan',
 'Unsecured loan',
 'Balance sheet total',
 'Gross block',
 'Revaluation reserve',
 'Accumulated depreciation',
 'Net block',
 'Capital work in progress',
 'Investments',
 'Current assets',
 'Current liabilities',
 'Book value of unquoted investments',
 'Market value of quoted investments',
 'Contingent liabilities',
 'Total Assets',
 'Working capital',
 'Lease liabilities',
 'Inventory',
 'Trade receivables',
 'Face value',
 'Cash Equivalents',
 'Advance from Customers',
 'Trade Payables',
 'Number of equity shares preceding year',
 'Debt preceding year',
 'Working capital preceding year',
 'Net block preceding year',
 'Gross block preceding year',
 'Capital work in progress preceding year',
 'Working capital 3Years back',
 'Working capital 5Years back',
 'Working capital 7Years back',
 'Working capital 10Years back',
 'Debt 3Years back',
 'Debt 5Years back',
 'Debt 7Years back',
 'Debt 10Years back',
 'Net block 3Years back',
 'Net block 5Years back',
 'Net block 7Years back',
 'Market Capitalization_bal',
 'join_key',
 'BSE Code_rat',
 'Current Price_rat',
 'Market Capitalization_rat',
 'Price to Earning',
 'Dividend yield',
 'Price to book value',
 'Return on assets',
 'Debt to equity',
 'Return on equity',
 'Promoter holding',
 'Earnings yield',
 'Pledged percentage',
 'Industry PE',
 'Enterprise Value',
 'Number of equity shares',
 'Book value',
 'Inventory turnover ratio',
 'Quick ratio',
 'Exports percentage',
 'Piotroski score',
 'G Factor',
 'Asset Turnover Ratio',
 'Financial leverage',
 'Number of Shareholders',
 'Unpledged promoter holding',
 'Return on invested capital',
 'Debtor days',
 'Industry PBV',
 'Credit rating',
 'Working Capital Days',
 'Earning Power',
 'Graham Number',
 'Cash Conversion Cycle',
 'Days Payable Outstanding',
 'Days Inventory Outstanding',
 'Public holding',
 'FII holding',
 'Change in FII holding',
 'Change in DII holding',
 'DII holding',
 'Book value preceding year',
 'Return on capital employed preceding year',
 'Return on assets preceding year',
 'Return on equity preceding year',
 'Number of Shareholders preceding quarter']

In [27]:
master.select_dtypes(include="object").columns.tolist()

/tmp/ipykernel_8585/2313172988.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  master.select_dtypes(include="object").columns.tolist()

['Name_bal', 'NSE Code_bal', 'Industry_bal', 'join_key']

In [28]:
X[[
    "Name_bal",
    "BSE Code_bal",
    "NSE Code_bal",
    "Industry_bal"
]].head()

,Name_bal,BSE Code_bal,NSE Code_bal,Industry_bal
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments
2,360 ONE,542772.0,360ONE,Finance & Investments
3,3B Blackbio,532067.0,__NA__,Healthcare
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small

In [37]:
master = master.drop(
    columns=[
        "Name_bal",
        "BSE Code_bal",
        "NSE Code_bal"
    ],
    errors="ignore"
)

In [38]:
[col for col in X.columns if "t_1" in col.lower()]

[]

In [39]:
[col for col in X.columns if "future" in col.lower()]

[]

In [40]:
X = master.drop(
    columns=["future_return"]
)

y = master["future_return"]

In [41]:
X.shape

(4667, 93)

In [42]:
X.columns.tolist()[-20:]

['Return on invested capital',
 'Debtor days',
 'Industry PBV',
 'Credit rating',
 'Working Capital Days',
 'Earning Power',
 'Graham Number',
 'Cash Conversion Cycle',
 'Days Payable Outstanding',
 'Days Inventory Outstanding',
 'Public holding',
 'FII holding',
 'Change in FII holding',
 'Change in DII holding',
 'DII holding',
 'Book value preceding year',
 'Return on capital employed preceding year',
 'Return on assets preceding year',
 'Return on equity preceding year',
 'Number of Shareholders preceding quarter']

In [43]:
X.columns.tolist()[:20]

['Industry_bal',
 'Current Price_bal',
 'Debt',
 'Equity capital',
 'Preference capital',
 'Reserves',
 'Secured loan',
 'Unsecured loan',
 'Balance sheet total',
 'Gross block',
 'Revaluation reserve',
 'Accumulated depreciation',
 'Net block',
 'Capital work in progress',
 'Investments',
 'Current assets',
 'Current liabilities',
 'Book value of unquoted investments',
 'Market value of quoted investments',
 'Contingent liabilities']

In [44]:
master.columns[
    master.columns.str.contains(
        "signal|future|t_1|price",
        case=False,
        regex=True
    )
]

Index(['Current Price_bal', 'Current Price_rat', 'Price to Earning',
       'Price to book value', 'future_return'],
      dtype='str')

In [45]:
X.isnull().mean().sort_values(ascending=False).head(20)

Credit rating                      1.000000
Days Payable Outstanding           0.357189
Days Inventory Outstanding         0.304907
Debt 10Years back                  0.286051
Working capital 10Years back       0.286051
Graham Number                      0.262053
Inventory turnover ratio           0.250054
Price to Earning                   0.223055
Net block 7Years back              0.202271
Debt 7Years back                   0.202271
Working capital 7Years back        0.202271
Working capital 5Years back        0.124277
Debt 5Years back                   0.124277
Net block 5Years back              0.124277
Return on equity preceding year    0.110992
Price to book value                0.105635
Book value preceding year          0.094493
Return on equity                   0.093208
Exports percentage                 0.081208
Debt to equity                     0.076709
dtype: float64

In [46]:
X = X.drop(columns=["Credit rating"], errors="ignore")

In [47]:
[col for col in X.columns if col.endswith("_rat")]

['BSE Code_rat', 'Current Price_rat', 'Market Capitalization_rat']

In [48]:
[col for col in X.columns if col.endswith("_bal")]

['Industry_bal', 'Current Price_bal', 'Market Capitalization_bal']

In [50]:
X = X.drop(
    columns=[
        "BSE Code_rat"
    ],
    errors="ignore"
)

In [52]:
X.shape

(4667, 91)

In [53]:
[
    col for col in X.columns
    if col.endswith("_rat")
]

['Current Price_rat', 'Market Capitalization_rat']

In [ ]:
X = X.drop(
    columns=[
        "Current Price_rat",
        "Market Capitalization_rat"
    ],
    errors="ignore"
)

In [55]:
[col for col in X.columns if "signal" in col.lower()]

[]

In [56]:
[col for col in X.columns if "future" in col.lower()]

[]

In [57]:
[col for col in X.columns if "t_1" in col.lower()]

[]

In [58]:
[col for col in X.columns if "price" in col.lower()]

['Current Price_bal', 'Price to Earning', 'Price to book value']

In [59]:
[col for col in X.columns if col.endswith("_rat")]

[]

In [60]:
[col for col in X.columns if col.endswith("_bal")]

['Industry_bal', 'Current Price_bal', 'Market Capitalization_bal']

In [61]:
X = X.rename(columns={
    "Industry_bal": "Industry",
    "Current Price_bal": "Current Price",
    "Market Capitalization_bal": "Market Capitalization"
})

In [66]:
X.shape

(4667, 89)

In [69]:
X = X.drop(columns=["join_key"], errors="ignore")

In [70]:
cat_cols = X.select_dtypes(include="object").columns

num_cols = X.select_dtypes(
    include=["int64","float64"]
).columns

print(cat_cols)
print(len(num_cols))

Index(['Industry'], dtype='str')
87

/tmp/ipykernel_8585/4278791258.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X.select_dtypes(include="object").columns

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [72]:
cat_cols = X_train.select_dtypes(
    include="object"
).columns

num_cols = X_train.select_dtypes(
    include=["int64","float64"]
).columns

print(cat_cols)
print(len(num_cols))

Index(['Industry'], dtype='str')
87

/tmp/ipykernel_8585/1795231725.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = X_train.select_dtypes(

In [73]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

num_pipe = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="median")
    )
])

cat_pipe = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(handle_unknown="ignore")
    )
])

preprocessor = ColumnTransformer([
    ("num", num_pipe, num_cols),
    ("cat", cat_pipe, cat_cols)
])

In [74]:
from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "regressor",
        RandomForestRegressor(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        )
    )
])

In [75]:
rf_model.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['Current Price', 'Debt', 'Equity capital', 'Preference capital',
       'Reserves', 'Secured loan', 'Unsecured loan', 'Balance sheet total',
       'Gross block', 'Revaluation reserve', 'Accumulated depreciation',
       'Net block', 'Capital work in progr...
       'Return on assets preceding year', 'Return on equity preceding year',
       'Number of Shareholders preceding quarter'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Industry'], dtype='str'))])),
                ('regressor',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [ ]:
y_pred_rf = rf_model.predict(X_test)

In [77]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae_rf = mean_absolute_error(
    y_test,
    y_pred_rf
)

mse_rf = mean_squared_error(
    y_test,
    y_pred_rf
)

rmse_rf = mse_rf ** 0.5

r2_rf = r2_score(
    y_test,
    y_pred_rf
)

print("MAE :", mae_rf)
print("RMSE:", rmse_rf)
print("R2  :", r2_rf)

MAE : 0.04541033081828668
RMSE: 0.05755905733462159
R2  : 0.35963054650271686

In [78]:
n = X_test.shape[0]
p = X_train.shape[1]

adj_r2_rf = (
    1 -
    (1-r2_rf)*(n-1)/(n-p-1)
)

adj_r2_rf

0.29294118329826613

In [79]:
from sklearn.linear_model import LinearRegression

lr_model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

lr_model.fit(X_train, y_train)

pred_lr = lr_model.predict(X_test)

r2_lr = r2_score(y_test, pred_lr)

r2_lr

-0.09977054266959717

In [80]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor

In [81]:
num_pipe_knn = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

cat_pipe_knn = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_knn = ColumnTransformer([
    ("num", num_pipe_knn, num_cols),
    ("cat", cat_pipe_knn, cat_cols)
])

knn_model = Pipeline([
    ("preprocessor", preprocessor_knn),
    ("regressor", KNeighborsRegressor(n_neighbors=5))
])

knn_model.fit(X_train, y_train)

pred_knn = knn_model.predict(X_test)

r2_knn = r2_score(y_test, pred_knn)

r2_knn

0.015627502170056595

In [82]:
from sklearn.ensemble import ExtraTreesRegressor

et_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "regressor",
        ExtraTreesRegressor(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        )
    )
])

et_model.fit(X_train, y_train)

pred_et = et_model.predict(X_test)

r2_et = r2_score(y_test, pred_et)

r2_et

0.3139105957059599

In [83]:
from xgboost import XGBRegressor

In [84]:
xgb_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "regressor",
        XGBRegressor(
            n_estimators=200,
            random_state=42,
            n_jobs=-1
        )
    )
])

xgb_model.fit(X_train, y_train)

pred_xgb = xgb_model.predict(X_test)

r2_xgb = r2_score(y_test, pred_xgb)

r2_xgb

0.3252905664466005

In [85]:
from catboost import CatBoostRegressor

In [86]:
cat_model = Pipeline([
    ("preprocessor", preprocessor),
    (
        "regressor",
        CatBoostRegressor(
            iterations=500,
            learning_rate=0.05,
            depth=6,
            random_state=42,
            verbose=0
        )
    )
])

cat_model.fit(X_train, y_train)

pred_cat = cat_model.predict(X_test)

r2_cat = r2_score(y_test, pred_cat)

r2_cat

0.3990750068043598

In [87]:
pd.DataFrame({
    "Model": [
        "Linear Regression",
        "KNN",
        "Random Forest",
        "Extra Trees",
        "XGBoost",
        "CatBoost"
    ],
    "R2": [
        r2_lr,
        r2_knn,
        r2_rf,
        r2_et,
        r2_xgb,
        r2_cat
    ]
}).sort_values(
    "R2",
    ascending=False
)

               Model        R2
5           CatBoost  0.399075
2      Random Forest  0.359631
4            XGBoost  0.325291
3        Extra Trees  0.313911
1                KNN  0.015628
0  Linear Regression -0.099771

In [89]:
from sklearn.model_selection import cross_val_score

cat_cv = cross_val_score(
    cat_model,
    X,
    y,
    cv=5,
    scoring="r2",
    n_jobs=-1
)

print(cat_cv)
print("Mean CV R2:", cat_cv.mean())
print("Std CV:", cat_cv.std())

[0.41949852 0.40036719 0.38422759 0.36883488 0.35108876]
Mean CV R2: 0.3848033875573125
Std CV: 0.023824295332057023

In [88]:
from sklearn.impute import KNNImputer

num_pipe_knn_imp = Pipeline([
    (
        "imputer",
        KNNImputer(n_neighbors=5)
    )
])

preprocessor_knn_imp = ColumnTransformer([
    ("num", num_pipe_knn_imp, num_cols),
    ("cat", cat_pipe, cat_cols)
])

In [91]:
cat_pipe_knn = Pipeline([
    (
        "imputer",
        SimpleImputer(strategy="most_frequent")
    ),
    (
        "encoder",
        OneHotEncoder(handle_unknown="ignore")
    )
])

preprocessor_knn = ColumnTransformer([
    ("num", num_pipe_knn, num_cols),
    ("cat", cat_pipe_knn, cat_cols)
])

cat_knn = Pipeline([
    ("preprocessor", preprocessor_knn),
    (
        "regressor",
        CatBoostRegressor(
            iterations=500,
            learning_rate=0.05,
            depth=6,
            random_state=42,
            verbose=0
        )
    )
])

cat_knn.fit(X_train, y_train)

pred_knn_imp = cat_knn.predict(X_test)

r2_knn_imp = r2_score(
    y_test,
    pred_knn_imp
)

print(r2_knn_imp)

0.3991141453326341

In [92]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [93]:
num_pipe_iter = Pipeline([
    (
        "imputer",
        IterativeImputer(
            random_state=42,
            max_iter=10
        )
    )
])

preprocessor_iter = ColumnTransformer([
    ("num", num_pipe_iter, num_cols),
    ("cat", cat_pipe_knn, cat_cols)
])

cat_iter = Pipeline([
    ("preprocessor", preprocessor_iter),
    (
        "regressor",
        CatBoostRegressor(
            iterations=500,
            learning_rate=0.05,
            depth=6,
            random_state=42,
            verbose=0
        )
    )
])

cat_iter.fit(X_train, y_train)

pred_iter = cat_iter.predict(X_test)

r2_iter = r2_score(
    y_test,
    pred_iter
)

print(r2_iter)

/home/ridhi/bigdata-env/lib/python3.14/site-packages/sklearn/impute/_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

0.39762706581739016

In [94]:
pd.DataFrame({
    "Imputer":[
        "Median",
        "KNN",
        "Iterative"
    ],
    "R2":[
        r2_cat,
        r2_knn_imp,
        r2_iter
    ]
}).sort_values(
    "R2",
    ascending=False
)

     Imputer        R2
1        KNN  0.399114
0     Median  0.399075
2  Iterative  0.397627

In [95]:
feature_names = (
    cat_model
    .named_steps["preprocessor"]
    .get_feature_names_out()
)

importances = (
    cat_model
    .named_steps["regressor"]
    .feature_importances_
)

fi_cat = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
})

fi_cat = fi_cat.sort_values(
    "importance",
    ascending=False
)

fi_cat.head(30)

                                           feature  importance
49                           num__Return on assets    7.628663
46                           num__Price to Earning    7.204829
50                             num__Debt to equity    6.496713
47                             num__Dividend yield    3.797976
51                           num__Return on equity    3.619463
79                      num__Change in FII holding    3.282067
63                                   num__G Factor    2.699593
0                               num__Current Price    2.640582
66                     num__Number of Shareholders    2.255433
73                              num__Graham Number    2.148024
53                             num__Earnings yield    2.060784
83  num__Return on capital employed preceding year    1.791191
68                 num__Return on invested capital    1.752779
48                        num__Price to book value    1.611701
69                                num__Debtor days    1.578029
60                                num__Quick ratio    1.540542
84            num__Return on assets preceding year    1.494936
72                              num__Earning Power    1.431672
82                  num__Book value preceding year    1.411412
86   num__Number of Shareholders preceding quarter    1.332514
35                num__Working capital 5Years back    1.281616
57                    num__Number of equity shares    1.239783
64                       num__Asset Turnover Ratio    1.141344
2                              num__Equity capital    1.136368
38                           num__Debt 3Years back    1.065078
71                       num__Working Capital Days    0.991675
67                 num__Unpledged promoter holding    0.968825
43                      num__Net block 5Years back    0.965187
1                                        num__Debt    0.962078
55                                num__Industry PE    0.944750

In [96]:
fi_cat["cumulative_importance"] = (
    fi_cat["importance"].cumsum()
)

fi_cat.head(30)

,feature,importance,cumulative_importance
49,num__Return on assets,7.628663,7.628663
46,num__Price to Earning,7.204829,14.833492
50,num__Debt to equity,6.496713,21.330205
47,num__Dividend yield,3.797976,25.128181
51,num__Return on equity,3.619463,28.747644
79,num__Change in FII holding,3.282067,32.029711
63,num__G Factor,2.699593,34.729304
0,num__Current Price,2.640582,37.369886
66,num__Number of Shareholders,2.255433,39.625319
73,num__Graham Number,2.148024,41.773343
53,num__Earnings yield,2.060784,43.834128
83,num__Return on capital employed preceding year,1.791191,45.625319
68,num__Return on invested capital,1.752779,47.378098
48,num__Price to book value,1.611701,48.989799
69,num__Debtor days,1.578029,50.567828
60,num__Quick ratio,1.540542,52.108370
84,num__Return on assets preceding year,1.494936,53.603306
72,num__Earning Power,1.431672,55.034978
82,num__Book value preceding year,1.411412,56.446389
86,num__Number of Shareholders preceding quarter,1.332514,57.778904
35,num__Working capital 5Years back,1.281616,59.060519
57,num__Number of equity shares,1.239783,60.300303
64,num__Asset Turnover Ratio,1.141344,61.441647
2,num__Equity capital,1.136368,62.578015
38,num__Debt 3Years back,1.065078,63.643093
71,num__Working Capital Days,0.991675,64.634768
67,num__Unpledged promoter holding,0.968825,65.603592
43,num__Net block 5Years back,0.965187,66.568780
1,num__Debt,0.962078,67.530857
55,num__Industry PE,0.944750,68.475608

In [97]:
top80 = fi_cat[
    fi_cat["cumulative_importance"] <= 80
]

top80.shape

(44, 3)

In [100]:
top80.head(44)

,feature,importance,cumulative_importance
49,num__Return on assets,7.628663,7.628663
46,num__Price to Earning,7.204829,14.833492
50,num__Debt to equity,6.496713,21.330205
47,num__Dividend yield,3.797976,25.128181
51,num__Return on equity,3.619463,28.747644
79,num__Change in FII holding,3.282067,32.029711
63,num__G Factor,2.699593,34.729304
0,num__Current Price,2.640582,37.369886
66,num__Number of Shareholders,2.255433,39.625319
73,num__Graham Number,2.148024,41.773343
53,num__Earnings yield,2.060784,43.834128
83,num__Return on capital employed preceding year,1.791191,45.625319
68,num__Return on invested capital,1.752779,47.378098
48,num__Price to book value,1.611701,48.989799
69,num__Debtor days,1.578029,50.567828
60,num__Quick ratio,1.540542,52.108370
84,num__Return on assets preceding year,1.494936,53.603306
72,num__Earning Power,1.431672,55.034978
82,num__Book value preceding year,1.411412,56.446389
86,num__Number of Shareholders preceding quarter,1.332514,57.778904
35,num__Working capital 5Years back,1.281616,59.060519
57,num__Number of equity shares,1.239783,60.300303
64,num__Asset Turnover Ratio,1.141344,61.441647
2,num__Equity capital,1.136368,62.578015
38,num__Debt 3Years back,1.065078,63.643093
71,num__Working Capital Days,0.991675,64.634768
67,num__Unpledged promoter holding,0.968825,65.603592
43,num__Net block 5Years back,0.965187,66.568780
1,num__Debt,0.962078,67.530857
55,num__Industry PE,0.944750,68.475608
62,num__Piotroski score,0.921977,69.397585
22,num__Inventory,0.909581,70.307166
58,num__Book value,0.905099,71.212265
65,num__Financial leverage,0.897943,72.110208
30,num__Working capital preceding year,0.860160,72.970367
52,num__Promoter holding,0.846456,73.816823
37,num__Working capital 10Years back,0.840333,74.657157
74,num__Cash Conversion Cycle,0.839141,75.496298
44,num__Net block 7Years back,0.824203,76.320501
5,num__Secured loan,0.793456,77.113957
41,num__Debt 10Years back,0.733413,77.847370
85,num__Return on equity preceding year,0.720322,78.567692
76,num__Days Inventory Outstanding,0.717856,79.285548
14,num__Current assets,0.693760,79.979308

In [101]:
top_features = (
    top80["feature"]
    .tolist()
)

len(top_features)

44

In [102]:
top_features_original = [
    col.replace("num__", "")
       .replace("cat__", "")
    for col in top_features
]

top_features_original[:20]

['Return on assets',
 'Price to Earning',
 'Debt to equity',
 'Dividend yield',
 'Return on equity',
 'Change in FII holding',
 'G Factor',
 'Current Price',
 'Number of Shareholders',
 'Graham Number',
 'Earnings yield',
 'Return on capital employed preceding year',
 'Return on invested capital',
 'Price to book value',
 'Debtor days',
 'Quick ratio',
 'Return on assets preceding year',
 'Earning Power',
 'Book value preceding year',
 'Number of Shareholders preceding quarter']

In [103]:
missing = [
    col
    for col in top_features_original
    if col not in X.columns
]

len(missing), missing[:10]

(0, [])

In [104]:
selected_features = [
    col
    for col in top_features_original
    if col in X.columns
]

X_reduced = X[selected_features]

X_reduced.shape

(4667, 44)

In [105]:
X_train_fs, X_test_fs, y_train_fs, y_test_fs = train_test_split(
    X_reduced,
    y,
    test_size=0.2,
    random_state=42
)

In [107]:
cat_cols_fs = X_reduced.select_dtypes(
    include="object"
).columns

num_cols_fs = X_reduced.select_dtypes(
    include=["int64", "float64"]
).columns

In [108]:
preprocessor_fs = ColumnTransformer([
    (
        "num",
        Pipeline([
            (
                "imputer",
                SimpleImputer(strategy="median")
            )
        ]),
        num_cols_fs
    ),
    (
        "cat",
        Pipeline([
            (
                "imputer",
                SimpleImputer(strategy="most_frequent")
            ),
            (
                "encoder",
                OneHotEncoder(
                    handle_unknown="ignore"
                )
            )
        ]),
        cat_cols_fs
    )
])

In [109]:
cat_fs = Pipeline([
    ("preprocessor", preprocessor_fs),
    (
        "regressor",
        CatBoostRegressor(
            iterations=500,
            learning_rate=0.05,
            depth=6,
            random_state=42,
            verbose=0
        )
    )
])

In [110]:
cat_fs.fit(
    X_train_fs,
    y_train_fs
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['Return on assets', 'Price to Earning', 'Debt to equity',
       'Dividend yield', 'Return on equity', 'Change in FII holding',
       'G Factor', 'Current Price', 'Number of Shareholders', 'Graham Number',
       'Earnings yield', 'Return on capital employed pre...
       'Return on equity preceding year', 'Days Inventory Outstanding',
       'Current assets'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='str'))])),
                ('regressor',
                 CatBoostRegressor(depth=6, iterations=500, learning_rate=0.05, loss_function='RMSE', random_state=42, verbose=0))])

In [111]:
pred_fs = cat_fs.predict(
    X_test_fs
)

r2_fs = r2_score(
    y_test_fs,
    pred_fs
)

print(r2_fs)

0.4022120642710535

In [112]:
top20_features = (
    fi_cat.head(20)["feature"]
    .str.replace("num__", "")
    .str.replace("cat__", "")
    .tolist()
)

top20_features = [
    c for c in top20_features
    if c in X.columns
]

len(top20_features)

20

In [113]:
X_top20 = X[top20_features]

X_top20.shape

(4667, 20)

In [114]:
from sklearn.model_selection import train_test_split

X_train_20, X_test_20, y_train_20, y_test_20 = train_test_split(
    X_top20,
    y,
    test_size=0.20,
    random_state=42
)

In [115]:
cat_cols_20 = X_top20.select_dtypes(
    include="object"
).columns

num_cols_20 = X_top20.select_dtypes(
    include=["int64", "float64"]
).columns

In [116]:
preprocessor_20 = ColumnTransformer([
    (
        "num",
        Pipeline([
            (
                "imputer",
                SimpleImputer(strategy="median")
            )
        ]),
        num_cols_20
    ),
    (
        "cat",
        Pipeline([
            (
                "imputer",
                SimpleImputer(strategy="most_frequent")
            ),
            (
                "encoder",
                OneHotEncoder(handle_unknown="ignore")
            )
        ]),
        cat_cols_20
    )
])

In [117]:
from catboost import CatBoostRegressor
from sklearn.metrics import r2_score

cat_20 = Pipeline([
    ("preprocessor", preprocessor_20),
    (
        "regressor",
        CatBoostRegressor(
            iterations=500,
            learning_rate=0.05,
            depth=6,
            random_state=42,
            verbose=0
        )
    )
])

In [118]:
cat_20.fit(
    X_train_20,
    y_train_20
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['Return on assets', 'Price to Earning', 'Debt to equity',
       'Dividend yield', 'Return on equity', 'Change in FII holding',
       'G Factor', 'Current Price', 'Number of Shareholders', 'Graham Number',
       'Earnings yield', 'Return on capital employed pre...
       'Book value preceding year',
       'Number of Shareholders preceding quarter'],
      dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index([], dtype='str'))])),
                ('regressor',
                 CatBoostRegressor(depth=6, iterations=500, learning_rate=0.05, loss_function='RMSE', random_state=42, verbose=0))])

In [119]:
pred_20 = cat_20.predict(
    X_test_20
)

r2_20 = r2_score(
    y_test_20,
    pred_20
)

print("Top 20 R2:", r2_20)

Top 20 R2: 0.39843626199142423

In [120]:
pd.DataFrame({
    "Feature_Set":[
        "All Features",
        "Top 44",
        "Top 20"
    ],
    "R2":[
        r2_cat,
        r2_fs,
        r2_20
    ]
}).sort_values(
    "R2",
    ascending=False
)

    Feature_Set        R2
1        Top 44  0.402212
0  All Features  0.399075
2        Top 20  0.398436

In [121]:
! pip install optuna

Collecting optuna
  Downloading optuna-4.9.0-py3-none-any.whl.metadata (15 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.18.4-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /home/ridhi/bigdata-env/lib/python3.14/site-packages (from optuna) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/ridhi/bigdata-env/lib/python3.14/site-packages (from optuna) (26.2)
Collecting sqlalchemy>=1.4.2 (from optuna)
  Downloading sqlalchemy-2.0.51-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting tqdm (from optuna)
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: PyYAML in /home/ridhi/bigdata-env/lib/python3.14/site-packages (from optuna) (6.0.3)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading mako-1.3.12-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /home/ridhi/bigdata-env/lib/python3.14/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Collecting greenlet>=1 (from sqlalchemy>=1.4.2->optuna)
  Downloading greenlet-3.5.2-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/ridhi/bigdata-env/lib/python3.14/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.9.0-py3-none-any.whl (425 kB)
Downloading alembic-1.18.4-py3-none-any.whl (263 kB)
Downloading sqlalchemy-2.0.51-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 7.9 MB/s  0:00:00 eta 0:00:01
Downloading greenlet-3.5.2-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (663 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 663.2/663.2 kB 7.0 MB/s  0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Downloading mako-1.3.12-py3-none-any.whl (78 kB)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, Mako, greenlet, colorlog, sqlalchemy, alembic, optuna
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [optuna]2m6/7 [optuna]]my]
Successfully installed Mako-1.3.12 alembic-1.18.4 colorlog-6.10.1 greenlet-3.5.2 optuna-4.9.0 sqlalchemy-2.0.51 tqdm-4.68.3

In [122]:
import optuna

from catboost import CatBoostRegressor

from sklearn.metrics import r2_score

In [123]:
def objective(trial):

    params = {

        "iterations": trial.suggest_int(
            "iterations",
            200,
            1200
        ),

        "depth": trial.suggest_int(
            "depth",
            3,
            10
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.30,
            log=True
        ),

        "l2_leaf_reg": trial.suggest_float(
            "l2_leaf_reg",
            1,
            20
        ),

        "random_strength": trial.suggest_float(
            "random_strength",
            0,
            10
        ),

        "loss_function": "RMSE",

        "verbose": 0,

        "random_state": 42
    }

    model = Pipeline([
        ("preprocessor", preprocessor_fs),
        (
            "regressor",
            CatBoostRegressor(**params)
        )
    ])

    scores = cross_val_score(
        model,
        X_reduced,
        y,
        cv=5,
        scoring="r2",
        n_jobs=-1
    )

    return scores.mean()

In [124]:
study = optuna.create_study(
    direction="maximize"
)

[I 2026-06-20 13:32:20,373] A new study created in memory with name: no-name-2bbe9ec2-1039-4054-a37b-6f487c9f428e

In [ ]:
study.optimize(
    objective,
    n_trials=30
)

[I 2026-06-20 13:33:01,469] Trial 0 finished with value: 0.3752815223372485 and parameters: {'iterations': 325, 'depth': 7, 'learning_rate': 0.1296462177531851, 'l2_leaf_reg': 16.35789490607075, 'random_strength': 2.2163370775307403}. Best is trial 0 with value: 0.3752815223372485.
[I 2026-06-20 13:33:15,661] Trial 1 finished with value: 0.3845590685386687 and parameters: {'iterations': 328, 'depth': 3, 'learning_rate': 0.049597085041574875, 'l2_leaf_reg': 5.8268345732275515, 'random_strength': 4.892923477220464}. Best is trial 1 with value: 0.3845590685386687.

In [ ]:
print(
    "Best CV R2:",
    study.best_value
)

print(
    study.best_params
)

In [ ]:
best_params = study.best_params

final_cat = Pipeline([
    ("preprocessor", preprocessor_fs),
    (
        "regressor",
        CatBoostRegressor(
            **best_params,
            verbose=0,
            random_state=42
        )
    )
])

In [ ]:
final_cat.fit(
    X_train_fs,
    y_train_fs
)

In [ ]:
from sklearn.metrics import r2_score

pred_final = final_cat.predict(
    X_test_fs
)

final_r2 = r2_score(
    y_test_fs,
    pred_final
)

print(final_r2)