In [3]:
import pandas as pd

In [4]:
balance = pd.read_csv("../data/raw/Balance_Sheet_final.csv")

In [5]:
balance.columns.tolist()

['Name',
 'BSE Code',
 'NSE Code',
 'Industry',
 'Current Price',
 'Debt',
 'Equity capital',
 'Preference capital',
 'Reserves',
 'Secured loan',
 'Unsecured loan',
 'Balance sheet total',
 'Gross block',
 'Revaluation reserve',
 'Accumulated depreciation',
 'Net block',
 'Capital work in progress',
 'Investments',
 'Current assets',
 'Current liabilities',
 'Book value of unquoted investments',
 'Market value of quoted investments',
 'Contingent liabilities',
 'Total Assets',
 'Working capital',
 'Lease liabilities',
 'Inventory',
 'Trade receivables',
 'Face value',
 'Cash Equivalents',
 'Advance from Customers',
 'Trade Payables',
 'Number of equity shares preceding year',
 'Debt preceding year',
 'Working capital preceding year',
 'Net block preceding year',
 'Gross block preceding year',
 'Capital work in progress preceding year',
 'Working capital 3Years back',
 'Working capital 5Years back',
 'Working capital 7Years back',
 'Working capital 10Years back',
 'Debt 3Years back',
 'Debt 5Years back',
 'Debt 7Years back',
 'Debt 10Years back',
 'Net block 3Years back',
 'Net block 5Years back',
 'Net block 7Years back',
 'Market Capitalization',
 'join_key']

In [6]:
balance.info()

<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 51 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Name                                     4668 non-null   str
 1   BSE Code                                 4668 non-null   float64
 2   NSE Code                                 4668 non-null   str
 3   Industry                                 4668 non-null   str
 4   Current Price                            4667 non-null   float64
 5   Debt                                     4652 non-null   float64
 6   Equity capital                           4632 non-null   float64
 7   Preference capital                       4559 non-null   float64
 8   Reserves                                 4652 non-null   float64
 9   Secured loan                             4559 non-null   float64
 10  Unsecured loan                           4559 non-null   float64
 11  Balance sheet total                      4652 non-null   float64
 12  Gross block                              4559 non-null   float64
 13  Revaluation reserve                      4559 non-null   float64
 14  Accumulated depreciation                 4559 non-null   float64
 15  Net block                                4652 non-null   float64
 16  Capital work in progress                 4652 non-null   float64
 17  Investments                              4652 non-null   float64
 18  Current assets                           4652 non-null   float64
 19  Current liabilities                      4652 non-null   float64
 20  Book value of unquoted investments       4559 non-null   float64
 21  Market value of quoted investments       4559 non-null   float64
 22  Contingent liabilities                   4559 non-null   float64
 23  Total Assets                             4652 non-null   float64
 24  Working capital                          4652 non-null   float64
 25  Lease liabilities                        4652 non-null   float64
 26  Inventory                                4652 non-null   float64
 27  Trade receivables                        4652 non-null   float64
 28  Face value                               4642 non-null   float64
 29  Cash Equivalents                         4652 non-null   float64
 30  Advance from Customers                   4559 non-null   float64
 31  Trade Payables                           4652 non-null   float64
 32  Number of equity shares preceding year   4541 non-null   float64
 33  Debt preceding year                      4614 non-null   float64
 34  Working capital preceding year           4614 non-null   float64
 35  Net block preceding year                 4614 non-null   float64
 36  Gross block preceding year               4585 non-null   float64
 37  Capital work in progress preceding year  4614 non-null   float64
 38  Working capital 3Years back              4466 non-null   float64
 39  Working capital 5Years back              4087 non-null   float64
 40  Working capital 7Years back              3723 non-null   float64
 41  Working capital 10Years back             3332 non-null   float64
 42  Debt 3Years back                         4466 non-null   float64
 43  Debt 5Years back                         4087 non-null   float64
 44  Debt 7Years back                         3723 non-null   float64
 45  Debt 10Years back                        3332 non-null   float64
 46  Net block 3Years back                    4466 non-null   float64
 47  Net block 5Years back                    4087 non-null   float64
 48  Net block 7Years back                    3723 non-null   float64
 49  Market Capitalization                    4668 non-null   float64
 50  join_key                                 4668 non-null   str
dtypes: float64(47), str(4)
memory usage: 1.8 MB

In [7]:
balance.describe()

,BSE Code,Current Price,Debt,Equity capital,Preference capital,Reserves,Secured loan,Unsecured loan,Balance sheet total,Gross block,...,Working capital 7Years back,Working capital 10Years back,Debt 3Years back,Debt 5Years back,Debt 7Years back,Debt 10Years back,Net block 3Years back,Net block 5Years back,Net block 7Years back,Market Capitalization
count,4668.000000,4667.000000,4.652000e+03,4632.000000,4559.000000,4652.000000,4559.000000,4.559000e+03,4.652000e+03,4.559000e+03,...,3.723000e+03,3332.000000,4.466000e+03,4.087000e+03,3.723000e+03,3.332000e+03,4466.000000,4087.000000,3723.000000,4.668000e+03
mean,475480.346187,604.471965,6.557444e+03,148.928025,3.197671,2070.425305,1286.856010,5.245291e+03,1.189545e+04,2.169847e+03,...,-5.367461e+02,436.761303,5.234997e+03,4.612096e+03,3.998112e+03,3.391740e+03,1191.164120,1118.383470,991.730975,9.528972e+03
std,158391.995050,3016.534502,1.044876e+05,1268.927764,38.644141,17494.441770,13333.733823,9.374735e+04,1.508403e+05,2.148023e+04,...,6.519484e+04,3655.670209,7.984172e+04,6.485755e+04,5.760334e+04,4.440673e+04,11614.810037,9929.943392,7319.531473,5.921956e+04
min,-1.000000,0.030000,0.000000e+00,0.000000,0.000000,-154286.600000,-21.530000,-2.365440e+03,0.000000e+00,0.000000e+00,...,-3.955107e+06,-20008.560000,-4.400000e-01,0.000000e+00,-1.080000e+00,-6.000000e-02,0.000000,0.000000,0.000000,5.000000e-02
25%,511311.250000,27.000000,1.607500e+00,6.017500,0.000000,4.790000,0.000000,4.000000e-02,3.499000e+01,3.755000e+00,...,2.035000e+00,1.767500,1.230000e+00,6.300000e-01,5.300000e-01,3.900000e-01,1.430000,1.670000,1.320000,3.669250e+01
50%,530908.000000,103.000000,2.103000e+01,12.815000,0.000000,51.155000,5.690000,3.750000e+00,1.562300e+02,4.094000e+01,...,1.883000e+01,16.075000,1.788000e+01,1.768000e+01,1.587000e+01,1.438000e+01,19.605000,21.790000,19.580000,1.958900e+02
75%,538996.250000,386.250000,1.469750e+02,30.000000,0.000000,454.125000,75.145000,3.326000e+01,1.045662e+03,3.526100e+02,...,1.034850e+02,94.482500,1.270400e+02,1.321300e+02,1.250200e+02,1.279150e+02,181.310000,182.615000,179.510000,1.721570e+03
max,590134.000000,128456.650000,5.606147e+06,50119.800000,1813.000000,786715.000000,639609.500000,4.966537e+06,6.733756e+06,1.017992e+06,...,2.790335e+05,127085.300000,4.149127e+06,3.354289e+06,2.936176e+06,2.062612e+06,541258.000000,398374.000000,198526.000000,2.114993e+06

In [8]:
ratios = pd.read_csv("../data/raw/ratios_1_final.csv")

ratios.head()

,Name,BSE Code,NSE Code,Industry,Current Price,Market Capitalization,Price to Earning,Dividend yield,Price to book value,Return on assets,...,FII holding,Change in FII holding,Change in DII holding,DII holding,Book value preceding year,Return on capital employed preceding year,Return on assets preceding year,Return on equity preceding year,Number of Shareholders preceding quarter,join_key
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.65,796.25,13.84,0.57,2.30,10.35,...,0.73,0.01,0.00,0.00,83.20,19.27,8.10,15.34,20546.0,533022.0_20MICRONS
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,73.96,2.30,3.54,1.39,64.72,...,0.00,0.00,0.00,0.00,18.87,-43.10,-38.53,-62.72,6333.0,526921.0_21STCENMGM
2,360 ONE,542772.0,360ONE,Finance & Investments,997.60,36199.65,45.05,1.63,10.36,6.11,...,63.22,0.74,-0.53,8.34,87.67,13.33,6.00,21.41,42622.0,542772.0_360ONE
3,3B Blackbio,532067.0,__NA__,Healthcare,1184.50,1016.66,31.66,0.21,4.54,13.89,...,2.97,-0.41,0.71,1.89,228.05,19.06,12.77,16.00,10088.0,532067.0___NA__
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,26.55,23.30,0.00,NaN,3.59,...,0.00,NaN,NaN,0.00,NaN,29.33,4.19,53.37,NaN,544190.0___NA__

In [9]:
ratios.columns.tolist()

['Name',
 'BSE Code',
 'NSE Code',
 'Industry',
 'Current Price',
 'Market Capitalization',
 'Price to Earning',
 'Dividend yield',
 'Price to book value',
 'Return on assets',
 'Debt to equity',
 'Return on equity',
 'Promoter holding',
 'Earnings yield',
 'Pledged percentage',
 'Industry PE',
 'Enterprise Value',
 'Number of equity shares',
 'Book value',
 'Inventory turnover ratio',
 'Quick ratio',
 'Exports percentage',
 'Piotroski score',
 'G Factor',
 'Asset Turnover Ratio',
 'Financial leverage',
 'Number of Shareholders',
 'Unpledged promoter holding',
 'Return on invested capital',
 'Debtor days',
 'Industry PBV',
 'Credit rating',
 'Working Capital Days',
 'Earning Power',
 'Graham Number',
 'Cash Conversion Cycle',
 'Days Payable Outstanding',
 'Days Receivable Outstanding',
 'Days Inventory Outstanding',
 'Public holding',
 'FII holding',
 'Change in FII holding',
 'Change in DII holding',
 'DII holding',
 'Book value preceding year',
 'Return on capital employed preceding year',
 'Return on assets preceding year',
 'Return on equity preceding year',
 'Number of Shareholders preceding quarter',
 'join_key']

In [10]:
ratios.info()

<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Data columns (total 50 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Name                                       4668 non-null   str
 1   BSE Code                                   4668 non-null   float64
 2   NSE Code                                   4668 non-null   str
 3   Industry                                   4668 non-null   str
 4   Current Price                              4667 non-null   float64
 5   Market Capitalization                      4668 non-null   float64
 6   Price to Earning                           3627 non-null   float64
 7   Dividend yield                             4642 non-null   float64
 8   Price to book value                        4174 non-null   float64
 9   Return on assets                           4606 non-null   float64
 10  Debt to equity                             4310 non-null   float64
 11  Return on equity                           4233 non-null   float64
 12  Promoter holding                           4653 non-null   float64
 13  Earnings yield                             4651 non-null   float64
 14  Pledged percentage                         4653 non-null   float64
 15  Industry PE                                4646 non-null   float64
 16  Enterprise Value                           4652 non-null   float64
 17  Number of equity shares                    4648 non-null   float64
 18  Book value                                 4540 non-null   float64
 19  Inventory turnover ratio                   3501 non-null   float64
 20  Quick ratio                                4647 non-null   float64
 21  Exports percentage                         4289 non-null   float64
 22  Piotroski score                            4668 non-null   float64
 23  G Factor                                   4668 non-null   float64
 24  Asset Turnover Ratio                       4606 non-null   float64
 25  Financial leverage                         4606 non-null   float64
 26  Number of Shareholders                     4591 non-null   float64
 27  Unpledged promoter holding                 4653 non-null   float64
 28  Return on invested capital                 4546 non-null   float64
 29  Debtor days                                4335 non-null   float64
 30  Industry PBV                               4659 non-null   float64
 31  Credit rating                              0 non-null      float64
 32  Working Capital Days                       4335 non-null   float64
 33  Earning Power                              4649 non-null   float64
 34  Graham Number                              3444 non-null   float64
 35  Cash Conversion Cycle                      4335 non-null   float64
 36  Days Payable Outstanding                   3001 non-null   float64
 37  Days Receivable Outstanding                4335 non-null   float64
 38  Days Inventory Outstanding                 3245 non-null   float64
 39  Public holding                             4591 non-null   float64
 40  FII holding                                4591 non-null   float64
 41  Change in FII holding                      4443 non-null   float64
 42  Change in DII holding                      4443 non-null   float64
 43  DII holding                                4591 non-null   float64
 44  Book value preceding year                  4226 non-null   float64
 45  Return on capital employed preceding year  4435 non-null   float64
 46  Return on assets preceding year            4540 non-null   float64
 47  Return on equity preceding year            4150 non-null   float64
 48  Number of Shareholders preceding quarter   4443 non-null   float64
 49  join_key                                   4668 non-null   str
dtypes: float64(46), str(4)
memory usage: 1.8 MB

In [11]:
balance.isnull().sum().sort_values(ascending=False).head(23)

Debt 10Years back                         1336
Working capital 10Years back              1336
Working capital 7Years back                945
Debt 7Years back                           945
Net block 7Years back                      945
Net block 5Years back                      581
Debt 5Years back                           581
Working capital 5Years back                581
Working capital 3Years back                202
Debt 3Years back                           202
Net block 3Years back                      202
Number of equity shares preceding year     127
Accumulated depreciation                   109
Gross block                                109
Advance from Customers                     109
Revaluation reserve                        109
Preference capital                         109
Unsecured loan                             109
Secured loan                               109
Contingent liabilities                     109
Book value of unquoted investments         109
Market value of quoted investments         109
Gross block preceding year                  83
dtype: int64

In [12]:
ratios.isnull().sum().sort_values(ascending=False).head(23)

Credit rating                                4668
Days Payable Outstanding                     1667
Days Inventory Outstanding                   1423
Graham Number                                1224
Inventory turnover ratio                     1167
Price to Earning                             1041
Return on equity preceding year               518
Price to book value                           494
Book value preceding year                     442
Return on equity                              435
Exports percentage                            379
Debt to equity                                358
Days Receivable Outstanding                   333
Working Capital Days                          333
Debtor days                                   333
Cash Conversion Cycle                         333
Return on capital employed preceding year     233
Change in FII holding                         225
Change in DII holding                         225
Number of Shareholders preceding quarter      225
Book value                                    128
Return on assets preceding year               128
Return on invested capital                    122
dtype: int64

In [13]:
t1 = pd.read_csv("../data/raw/t1_prices.csv")

t1.head()

              join_key  t_1_price
0   533022.0_20MICRONS     229.42
1  526921.0_21STCENMGM      72.33
2      542772.0_360ONE    1025.83
3      532067.0___NA__    1329.94
4      544190.0___NA__      45.14

In [14]:
balance[['join_key', 'Current Price']].head()

              join_key  Current Price
0   533022.0_20MICRONS         225.45
1  526921.0_21STCENMGM          70.44
2      542772.0_360ONE         999.10
3      532067.0___NA__        1194.20
4      544190.0___NA__          44.10

In [15]:
master = (
    balance
    .merge(ratios, on="join_key", suffixes=("_bal", "_rat"))
    .merge(t1, on="join_key")
)

master.shape

(4668, 101)

In [16]:
master.head()

,Name_bal,BSE Code_bal,NSE Code_bal,Industry_bal,Current Price_bal,Debt,Equity capital,Preference capital,Reserves,Secured loan,...,FII holding,Change in FII holding,Change in DII holding,DII holding,Book value preceding year,Return on capital employed preceding year,Return on assets preceding year,Return on equity preceding year,Number of Shareholders preceding quarter,t_1_price
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.45,121.37,17.64,0.0,335.31,82.32,...,0.73,0.01,0.00,0.00,83.20,19.27,8.10,15.34,20546.0,229.42
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,4.17,10.50,0.0,42.88,0.00,...,0.00,0.00,0.00,0.00,18.87,-43.10,-38.53,-62.72,6333.0,72.33
2,360 ONE,542772.0,360ONE,Finance & Investments,999.10,9471.93,35.89,0.0,3413.84,7636.08,...,63.22,0.74,-0.53,8.34,87.67,13.33,6.00,21.41,42622.0,1025.83
3,3B Blackbio,532067.0,__NA__,Healthcare,1194.20,0.85,8.57,0.0,214.48,1.12,...,2.97,-0.41,0.71,1.89,228.05,19.06,12.77,16.00,10088.0,1329.94
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,13.40,0.36,0.0,3.74,9.54,...,0.00,NaN,NaN,0.00,NaN,29.33,4.19,53.37,NaN,45.14

In [17]:
master.info()

<class 'pandas.DataFrame'>
RangeIndex: 4668 entries, 0 to 4667
Columns: 101 entries, Name_bal to t_1_price
dtypes: float64(94), str(7)
memory usage: 3.6 MB

In [18]:
master["future_return"] = (
    (master["t_1_price"] - master["Current Price_bal"])
    / master["Current Price_bal"]
)

In [19]:
master["future_return"].describe()

count    4667.000000
mean       -0.007323
std         0.072014
min        -0.239105
25%        -0.056594
50%        -0.008838
75%         0.040610
max         0.273827
Name: future_return, dtype: float64

In [20]:
def label_return(x):
    if x > 0.05:
        return "Buy"
    elif x < -0.05:
        return "Sell"
    else:
        return "Hold"

master["signal"] = master["future_return"].apply(label_return)

master["signal"].value_counts()

signal
Hold    2362
Sell    1314
Buy      992
Name: count, dtype: int64

In [21]:
df = master.copy()

drop_cols = [
    "Name_bal",
    "BSE Code_bal",
    "NSE Code_bal",
    "join_key"
]

df = df.drop(columns=drop_cols)

df.shape

(4668, 99)

In [22]:
[col for col in df.columns if "_bal" in col or "_rat" in col][:50]

['Industry_bal',
 'Current Price_bal',
 'Market Capitalization_bal',
 'Name_rat',
 'BSE Code_rat',
 'NSE Code_rat',
 'Industry_rat',
 'Current Price_rat',
 'Market Capitalization_rat']

In [23]:
(df["Industry_bal"] == df["Industry_rat"]).all()

np.True_

In [24]:
(df["Current Price_bal"] == df["Current Price_rat"]).all()

np.False_

In [25]:
(df["Market Capitalization_bal"] == df["Market Capitalization_rat"]).all()

np.False_

In [26]:
(df["Current Price_bal"] - df["Current Price_rat"]).describe()

count    4667.000000
mean        0.099912
std         7.181826
min       -83.250000
25%         0.000000
50%         0.000000
75%         0.000000
max       328.500000
dtype: float64

In [27]:
(df["Market Capitalization_bal"] - df["Market Capitalization_rat"]).describe()

count    4668.000000
mean       -3.608085
std       110.601811
min     -5581.800000
25%         0.000000
50%         0.000000
75%         0.000000
max       723.610000
dtype: float64

In [28]:
df = df.drop(columns=[
    "Name_rat",
    "BSE Code_rat",
    "NSE Code_rat",
])

In [29]:
df = df.rename(columns={
    "Industry_bal": "Industry",
    "Current Price_bal": "Current Price",
    "Market Capitalization_bal": "Market Capitalization"
})

df.shape

(4668, 96)

In [30]:
missing_pct = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_pct.head(25)

Credit rating                                100.000000
Days Payable Outstanding                      35.711225
Days Inventory Outstanding                    30.484147
Working capital 10Years back                  28.620394
Debt 10Years back                             28.620394
Graham Number                                 26.221080
Inventory turnover ratio                      25.000000
Price to Earning                              22.300771
Working capital 7Years back                   20.244216
Debt 7Years back                              20.244216
Net block 7Years back                         20.244216
Debt 5Years back                              12.446444
Net block 5Years back                         12.446444
Working capital 5Years back                   12.446444
Return on equity preceding year               11.096829
Price to book value                           10.582691
Book value preceding year                      9.468723
Return on equity                               9.318766
Exports percentage                             8.119109
Debt to equity                                 7.669237
Debtor days                                    7.133676
Cash Conversion Cycle                          7.133676
Days Receivable Outstanding                    7.133676
Working Capital Days                           7.133676
Return on capital employed preceding year      4.991431
dtype: float64

In [31]:
master[["Current Price_bal","t_1_price"]].head()

   Current Price_bal  t_1_price
0             225.45     229.42
1              70.44      72.33
2             999.10    1025.83
3            1194.20    1329.94
4              44.10      45.14

In [32]:
master.to_csv("../data/processed/master.csv", index=False)